### ISSUE TITLE
  Uncaught Exception: SOAP Fault: HTTP

### ISSUE THREAD

**Issue by gusgeek** [AfipSDK/afip.php#76]
Buenas tardes, estoy teniendo este error

```
<b>Fatal error</b>:  Uncaught Exception: SOAP Fault: HTTP
Could not connect to host
 in /var/www/html/app/plataform/services/afip/Afip.php:402
Stack trace:
#0 /var/www/html/app/plataform/services/afip/Afip.php(382): AfipWebService-&gt;_CheckErrors()
#1 /var/www/html/app/plataform/services/afip/Class/ElectronicBilling.php(306): AfipWebService-&gt;ExecuteRequest()
#2 /var/www/html/app/plataform/services/afip/Class/ElectronicBilling.php(41): ElectronicBilling-&gt;ExecuteRequest()
#3 /var/www/html/app/plataform/framework/notadeventa/post.php(167): ElectronicBilling-&gt;GetLastVoucher()
#4 {main}
  thrown in <b>/var/www/html/app/plataform/services/afip/Afip.php</b> on line <b>402</b><br />
```

Quisiera saber si acaso sea un problema con AFIP o si es que tengo que corregir algo. Capas a alguien ya le sucedió. Gracias y Saludos.

**Comment by ivanalemunioz** [comment]
Issue ya existe #5
